### ISSUE TITLE
v0.3.0 error in klayout package manager

### ISSUE THREAD

**Issue by kdotom** [gdsfactory/klive#10]
The following error shows up when attempting to install v0.3.0 via the package manager.

"Error fetching spec file for package 'klive': Error 404: Not Found, fetching http://sami.klayout.org/git+https://github.com/gdsfactory/klive.git+klayout[v0.3.0]/grain.xml"

**Comment by sebastian-goeldi** [comment]
See https://github.com/gdsfactory/klive/issues/9

**Comment by sebastian-goeldi** [comment]
This is not something I can fix or mitigate or even influence from klive. Closing the issue again.

**Comment by kdotom** [comment]
> See #9

This is confirmation that the proposed solution works. If there's a firewall issue with klayout, a manual workaround (e.g. directly copying files) may be necessary, but if all is clear, this solution works.
