### ISSUE TITLE
Error fetching spec file for package 'klive'

### ISSUE THREAD

**Issue by Lyndon-Cao** [gdsfactory/klive#9]
fail to install klive 0.3.0 from klayout.
the reason is Error fetching spec file for package 'klive'.
![Screenshot from 2024-02-24 09-36-28](https://github.com/gdsfactory/klive/assets/50670305/24d4b8e2-687e-4b51-86ce-90ee6ef7c8f9)

 OS: Ubuntu
 Klayout version: 0.28.5
Expected klive version: 0.3.0

**Comment by sebastian-goeldi** [comment]
Hi, unfortunately I can't upload new packages to klayout with the old svn bridge anymore. Please update klayout to a new version >=0.28.13. See this for an in depth explanation https://www.klayout.de/forum/discussion/2399/red-alert-klayout-package-manager-will-stop-working-beginning-of-2024-with-github-hosted-packages

**Comment by Lyndon-Cao** [comment]
the problem is solved after klayout is upgraded to 0.28.17
